config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    member do
      post 'set_role'
    end
  end
  root :to => 'posts#index'
  resources :posts do
    resources :comments
  end
  get 'home/show_user'
  get 'home/banned'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_presence_of :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, only: [:create]
    before_action :check_post, only: [:create]

    def comment_params
        params.require(:comment).permit(:content)
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.user = current_user
        @comment.post = @post

        respond_to do |format|
            if @comment.save
                format.html { redirect_to @comment.post, notice: "Komentar je bil uspešno objavljen." }
            else
                format.html { redirect_to @comment.post, notice: "Prišlo je do napake pri objavljanju komentarja" }
            end
        end
    end

    private
    
        def check_post
            @post = Post.find(params[:post_id])
            redirect_to @post, notice: "Ta objava je izbrisana, zato komentiranje ni mogoče." if @post.marked_deleted?
        end

end

app/views/comments/_comment.html.erb
<div class="card">
    <div class="card-body">
        <% if comment.user.nil? %>
        <h5 class="d-inline-block text-danger">[IZBRISAN UPORABNIK]</h5>
        <% else %>
        <a href="/users/<%= comment.user.id %>" class="text-reset text-decoration-none d-inline-block">
            <div>
            <% if comment.user.avatar.attached? %>
                <img class="rounded-circle d-inline-block" width="32px" height="32px" src="<%=(url_for(comment.user.avatar))%>">
            <% end %>
            
            <h5 class="d-inline-block"><%= render "layouts/username", duser: comment.user %></h5>
            </div>
        </a>
        <% end %>
        <span class="float-end"><%= comment.created_at.strftime('%a, %d. %b %Y | %H:%M:%S') %></span>
    </div>
    <div class="card-body">
        <pre><%= comment.content %></pre>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url: post_comments_path(@post)) do |form| %>

  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <h5><strong>Nov komentar</strong></h5>
      <div>
        <%= form.text_area :content, placeholder: "Vsebina komentarja", class: "form-control", rows: 4 %>
      </div>


      <br/>
      <div class="form-row text-center">
        <%= form.submit class: "btn btn-primary", value: "Ustvari komentar" %>
      </div>
    </div>
  </div>
<% end %>