config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    member do
      post 'set_role'
    end
  end
  root :to => 'posts#index'
  resources :posts do
    resources :comments
  end
  get 'home/show_user'
  get 'home/banned'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  validates_presence_of :email
  validates_presence_of :username
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  has_one_attached :avatar

  attr_readonly :email

  # Validate user's profile image
  validate :validate_avatar
  
  # If user owns a particular post
  def owns?(post)
    !post.nil? && !post.user.nil? && post.user == self
  end

  # If the user is banned
  def banned?
    self.role == 0
  end

  # If the user is a regular user (not a mod, banned, or admin)
  def regular?
    self.role == 1
  end

  # If a user is a mod
  def mod?
    self.role == 2
  end

  # If a user is an admin
  # The only difference between mods and admins is
  # that admins can remove or add mods
  def admin?
    self.role == 3
  end

  # If a user has the authority over other users
  # for example, if a user can be banned, posts deleted, or hidden ...
  def has_authority?
    self.role >= 2
  end

  def has_authority_over?(target)
    has_authority? && (target.nil? || self.role > target.role)
  end

  # Returns a string representation of a role
  def role_str
    case self.role
    when 0
      'banned'
    when 1
      'regular user'
    when 2
      'mod'
    when 3
      'admin'
    else
      'unknown'
    end
  end

  # Returns a color of a particular role
  def role_color
    case self.role
    when 0
      'text-danger'
    when 2
      'text-success'
    when 3
      'text-warning'
    else
      'text-black'
    end
  end

  # Prevent user from authenticating if banned
  def active_for_authentication?
    super && !banned?
  end

  # Show message for banned users
  def inactive_message
    banned? ? "Your account is banned" : super
  end

  def has_post_authority?(post)
    !post.nil? && (self == post.user || has_authority_over?(post.user))
  end

  private
    def validate_avatar
      err = check_zaic_img(self.avatar)
      unless err.nil?
        self.avatar.purge
        errors.add(:avatar, err)
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :set_role]
    before_action :can_change_role, only: [:set_role]

    def show
        #@user = User.find(params[:id])
    end

    def set_role
        #@user = User.find(params[:id])

        respond_to do |format|
            if @user.update(role_params)
                format.html { redirect_to user_url(@user), notice: "Uporabnik je bil uspešno posodobljen." }
                format.json { render :show, status: :ok, location: @user }
            else
                format.html { render :show, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        def role_params
            params.permit(:role)
        end

        def require_admin
            user_signed_in? && current_user.admin?
        end

        def set_user
            @user = User.find(params[:id])
        end

        def can_change_role
            newparams = role_params
            rol = newparams["role"].to_i
            if !current_user.has_authority?
                redirect_to user_url(@user), notice: "Za spreminjanje ostalih uporabnikov so potrebne posebne pravice."
            elsif rol < 0 || rol > 2
                # handle invalid role error
                redirect_to user_url(@user), notice: "Neveljavna sprememba."
            elsif @user == current_user
                # handle modify yourself error
                redirect_to user_url(@user), notice: "Sprememba lastnega statusa ni dovoljena."
            elsif ((rol == 2 || @user.mod?) && !current_user.admin?) || @user.admin?
                # handle insufficient privileges
                redirect_to user_url(@user), notice: "Nimate dovolj pravic za spreminjanje tega uporabnika."
            end
        end

end

app/views/users/show.html.erb
<% if !@user.nil? %>
    <div class="mt-4 p-5 graybg text-black rounded">
        <h3><%= render "layouts/username", duser: @user %></h3>
        <hr>
        <br/>
        <table>
            <tr>
                <% if @user.avatar.attached? %>
                    <td class="tableimg">
                        <img class="rounded-circle d-inline-block" width="128px" height="128px" src="<%=(url_for(@user.avatar))%>">
                    </td>
                <% end %>
                <td class="align-top">
                    <p>Email: <%= @user.email %></p>
                </td>
            </tr>
        </table>
        <% if user_signed_in? && current_user != @user && current_user.has_authority_over?(@user) %>
            <% if @user.banned? %>
                <%= button_to "Unban", set_role_user_path(@user, role: 1), :method => :post, 'data-turbo': false %>
            <% else %>
                <%= button_to "Ban", set_role_user_path(@user, role: 0), :method => :post, 'data-turbo': false %>
            <% end %>

            <% if current_user.admin? %>
                <br/>
                <% if @user.mod? %>
                    <%= button_to "Demote to regular user", set_role_user_path(@user, role: 1), :method => :post, 'data-turbo': false %>
                <% else %>
                    <%= button_to "Promote to mod", set_role_user_path(@user, role: 2), :method => :post, 'data-turbo': false %>
                <% end %>
            <% end %>
        <% end %>
    </div>
<% end %>